### ISSUE TITLE
Support Bootstrap JS components

### ISSUE THREAD

**Issue by mvasilkov** [kupriyanenko/jbone#1]
Good time of day.

Is there (or will there be) support for [Bootstrap JS components](http://getbootstrap.com/javascript/), by any chance? That would be great, since Backbone+Bootstrap is a popular front-end combination used by many developers.

(Word of apology: I haven't tried it.)

**Comment by devel-pa** [comment]
To support Bootstrap jBone have to support delegate events.

**Comment by vitaly87** [comment]
Hi, I want to be updated, dose the jbone have bootstrap support?
