### ISSUE TITLE
Add show/hide and enabled/disabled

### ISSUE THREAD

**Issue by wwwboy** [kupriyanenko/jbone#13]
Т.к ВВ используется по большей части для одностраничных приложений, а приложения всегда работают с формами, а формы с данными и наиболее частыми операциями с элементами являются данные 4 оператора - нельзя ли их добавить в библиотеку?

**Comment by redaxmedia** [comment]
This can't be closed?

**Comment by kupriyanenko** [comment]
no, I think should be.
