### ISSUE TITLE
preventDefault in eventHandlers like in jQuery with "return false"

### ISSUE THREAD

**Issue by budarin** [kupriyanenko/jbone#28]
there need to cancel future event bubbling with "return false" like in jQuery.
I'm not able to cancel event from futher propagation and bubbling (
how to?

**Comment by kupriyanenko** [comment]
If you have the problems still, maybe event handler was added on the same element (Backbone do it in View for performance optimisations), in this case you can use `e.stopImmediatePropagation()`.

Example 1

```javascript
$('body').on('click', 'span', function(e) {
    e.stopPropagation();
    console.log('click');
});
$('body').on('click', 'span', function(e) {
    console.log('click');
});

// result:
// click
// click
```

Example 2

```javascript
$('body').on('click', 'span', function(e) {
    e.stopImmediatePropagation();
    console.log('click');
});
$('body').on('click', 'span', function(e) {
    console.log('click');
});

// result:
// click
```
