### ISSUE TITLE
Request to extend jBone with add() method

### ISSUE THREAD

**Issue by redaxmedia** [kupriyanenko/jbone#37]
Hello,

it would be nice to have the add() method for object collections in the jBone core.

I looked into jQuery:

https://github.com/jquery/jquery/blob/10399ddcf8a239acc27bdec9231b996b178224d3/src/traversing.js#L112

<pre>
add: function( selector, context ) {
	return this.pushStack(
		jQuery.unique(
			jQuery.merge( this.get(), jQuery( selector, context ) )
		)
	);
}
</pre>

And rebuild it for jBone:

https://github.com/redaxmedia/jbone-extend/blob/master/add.js

<pre>
jBone.fn.add = function(selector, context) {
	return jBone.merge(this, jBone(selector, context));
};
</pre>

Let me know what you think. Consider to link my jbone-extend repo inside your Readme :-)

**Comment by kupriyanenko** [comment]
Hi @redaxmedia, yes, I think it can be very useful, I think I can add it today/tomorrow.

**Comment by redaxmedia** [comment]
:+1:

**Comment by redaxmedia** [comment]
Your extend branche looks very promising, let me know if I can help you with testing.

**Comment by kupriyanenko** [comment]
Implemented.

**Comment by redaxmedia** [comment]
There is a typo <code>dspan</code> instead of <code>span</code>

**Comment by kupriyanenko** [comment]
it's div + span :)
