### ISSUE TITLE
Suggestion to move "perf" folder to "jbone-perf" repo

### ISSUE THREAD

**Issue by redaxmedia** [kupriyanenko/jbone#38]
I wonder why I have the <code>perf</code> folder inside my <code>bower-components</code>, maby it would be slightly more accurate to move the "perf testing suite" to another repo like <code>jbone-perf</code> to fullfill the separation of concern?

**Comment by kupriyanenko** [comment]
Hi @redaxmedia,

Thanks for comments, I will think about it, if it's common practice in JS world, I will do it.

**Comment by kupriyanenko** [comment]
Unnecessary folders added to bower ignore files.

**Comment by redaxmedia** [comment]
Well done
