### ISSUE TITLE
Performance issues found with on()

### ISSUE THREAD

**Issue by redaxmedia** [kupriyanenko/jbone#39]
Hey,

while working on a pageflip project, I found performance issues with jBone's event handling.

1. The pageflip container renders left and right pages
1. Mousemove and Touchmove events get attached on each refresh / rendering using on() 
1. The events with the same anonymous function handler get frequently added and <strong>not summerized</strong>
1. Browser slows down after fliping couple of pages

I made a jsPerf to demonstrate the problem: http://jsperf.com/jquery-on-vs-native/17
What is a pageflip: http://tympanus.net/Development/FlipboardPageLayout

**Comment by kupriyanenko** [comment]
Hi @redaxmedia, yes currently jbone have no any aggregation for the same event handlers and I think it's should be improved.

But please clarify, why you add so much event listeners in your application? what do you mean by "on each refresh / rendering using on()". As far as I understand you should add event listener for mousemove/touchmove events only once for parent element.

**Comment by redaxmedia** [comment]
You are right, I should add the events only once to the parent container as the refresh / render process in my case only replaces the content of the pageflip container.

However, I hope you can find a quick win to fix this.

**Comment by kupriyanenko** [comment]
@redaxmedia performance improved, will be available in the next release.

**Comment by kupriyanenko** [comment]
Released in [1.0.23](https://github.com/kupriyanenko/jbone/releases/tag/1.0.23)

**Comment by redaxmedia** [comment]
Great work!
