### ISSUE TITLE
No addClass / hasClass / removeClass

### ISSUE THREAD

**Issue by andreszs** [kupriyanenko/jbone#40]
Lack of classes manipulation render this library almost totally obsolete for production. Please update it if you want to see more users cliking the Star button on this project.

**Comment by kupriyanenko** [comment]
Hi @andreszs,

I added this methods, but you should understand that it's implemented via [Element.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList), and you can use it only with [modern browsers](http://caniuse.com/#search=classlist), if you want use it with old browsers, you should add shim for classList. I will add it to README soon.

**Comment by kupriyanenko** [comment]
Released in [1.0.23](https://github.com/kupriyanenko/jbone/releases/tag/1.0.23)
