### ISSUE TITLE
IE 11 raises error in jBone.contains function

### ISSUE THREAD

**Issue by budarin** [kupriyanenko/jbone#41]
jBone.contains = function(container, contained) {
    var result;
    container.reverse().some(function(el) {
        if (el.contains(contained)) {      //<------ error: Object doesn't support property or method 'contains'
            return result = el;
        }
    });
    return result;
};

**Comment by budarin** [comment]
sorry it's my bug.
Please delete the issue

**Comment by kupriyanenko** [comment]
Hi @budarin, ok, thanks.

**Comment by alexandrbig** [comment]
Hello, actually I have the same issue in IE11.
What was the solution to fix it?

version jBone v1.0.28

**Comment by budarin** [comment]
Sorry, I don't remember the context but it was not the library's problem

**Comment by kupriyanenko** [comment]
Hi @alexandrbig, could you show example of usage `.contains`.

**Comment by alexandrbig** [comment]
http://screencast.com/t/qS1SDLUa

It seems I've added $(document).on(...) and it calls dispatch method.

**Comment by alexandrbig** [comment]
It seems that my issue is not the same, but similar
I've got error in line 399:
> (el !== e.target && el.contains(e.target))

**Comment by alexandrbig** [comment]
Hello, the problem is in absense of `contains` method for `document` in IE but `document.body` has this method.
So `$(document).on(...)` may not work in IE but `$(document.body).on(...)` will do.
