### ISSUE TITLE
Add method is returning native array / breaks traversing

### ISSUE THREAD

**Issue by redaxmedia** [kupriyanenko/jbone#43]
I just updated to the latest jBone release and removed my jbone-extend micro lib, then I run to a bunch of errors in my testing suite.

First testing:
<pre>
$('&lt;div&gt;').add('&lt;span&gt;');
</pre>

<strong>Actual:</strong>: Array[div, span]
<strong>Expected:</strong> Object[div, span]

Second testing:
<pre>
$('&lt;div&gt;').add('&lt;span&gt;').addClass('test');
</pre>

<strong>Actual:</strong>: addClass is not a function
<strong>Expected:</strong> Object[div.test, span.test]

PS: I suggest to add a global integration test that is using all methods inside fn. and tests the traversing for each of them.

BTW: You are using "semantic versioning" in a wrong way, if you added new features you have to bump the minor and not the patch number... :-)

**Comment by kupriyanenko** [comment]
@redaxmedia got it, need to fix.

**Comment by kupriyanenko** [comment]
- [x] Fix `jBone.fn.add`
- [ ] Add tests for traversing

**Comment by redaxmedia** [comment]
Great!

**Comment by kupriyanenko** [comment]
Released in [1.0.24](https://github.com/kupriyanenko/jbone/releases/tag/1.0.24)
