### ISSUE TITLE
[1.0.26] jBone.contains fails when container is not an array of elements

### ISSUE THREAD

**Issue by devel-pa** [kupriyanenko/jbone#46]
Like this, where `el` is from a view.

```
jBone.contains(document.documentElement, el)
```

**Comment by kupriyanenko** [comment]
Hi @devel-pa,

Fixed and will be released soon, but better to use native `.contains` method, see https://developer.mozilla.org/en/docs/Web/API/Node/contains

**Comment by devel-pa** [comment]
Thanks, I'll check that too.

**Comment by kupriyanenko** [comment]
Released in [1.0.27](https://github.com/kupriyanenko/jbone/releases/tag/1.0.27)

**Comment by devel-pa** [comment]
Still crashing if container is an array.
My patch:

```
jBone.contains = function(container, contained) {
  var result;
  var contains = function(el) {
    if (el.contains(contained)) {
      return result = el;
    }
  };

  if(container.reverse) {
    container.reverse().some(contains);
  }
  else {
    contains(container);
  }

  return result;
}
```

**Comment by kupriyanenko** [comment]
I think for you better to improve `.find()` method and add support for [searching by element](https://api.jquery.com/find/#find-element).

Because `jBone.contains` should work only with DOM elements, not with array or collections ([documentation](https://api.jquery.com/jQuery.contains/)) and looks like polyfill for native `.contains`, so I plan to remove it from jBone #48 

And if you want to contribute code, welcome for pull requests :)

**Comment by devel-pa** [comment]
The method is used by Marionette. Another idea is to override it in jbone-extend and no issue when you'll remove it from jbone.

**Comment by devel-pa** [comment]
I have to investigate a bit more, I don't know why I have an array of elements.

**Comment by kupriyanenko** [comment]
Ah, ok, then will keep it.

But override method logic is bad idea. jQuery doesn't take array for `$.contains` method, why `.find()` method is not suitable for you?

**Comment by devel-pa** [comment]
`.find` is fine for me, just Marionette is using the contains. Maybe I was looking in the wrong place. I have no idea. I'll investigate this evening to see why I need that patch as now looks for me like it make no sense.

**Comment by kupriyanenko** [comment]
ok, so

1. Need to keep `$.contains` method in jBone.
2. Need to add new case for `.find()` method (allow find by DOM node).

**Comment by devel-pa** [comment]
Looks like for whatever reason I've put this stupid line in my code:

```
jBone.contains(jBone(document.documentElement), el)
```
