### ISSUE TITLE
version 1.1.13 @ npm

### ISSUE THREAD

**Issue by tomaszlukasik** [kupriyanenko/jbone#53]
Hi,
Looks like there is something messed up with versions in npm registry.
```
npm info jbone
```
shows versions list:
```
[ '1.0.7',
...,
 '1.0.12',
'1.0.15',
...,
'1.0.28',
'1.1.13' ],
```
The **1.1.13** is probably the missing **1.0.13**.
It's not a problem if you are limiting to minor version (~1.0.28), but becomes a problem with more relaxed matching (eg. ^1.0.28). And it simply shouldn't be like this :)

**Comment by kupriyanenko** [comment]
Hi @tomaszlukasik ,

Thank you very much, unpublished.
