### ISSUE TITLE
Trigger of multiple events are different from jQuery and Zepto

### ISSUE THREAD

**Issue by henryruhs** [kupriyanenko/jbone#54]
I found this issue while writing unit tests that run again jBone, jQuery and Zepto.

<pre>
$(element).trigger('mouseenter mouseleave');
</pre>

In jBone both Events get fired one after another.

In jQuery and Zepto none of the events get fired - the trigger method supports only a single event.

**Comment by kupriyanenko** [comment]
@redaxmedia agree with you, will be fixed
