### ISSUE TITLE
Add the ability to create custom build

### ISSUE THREAD

**Issue by kupriyanenko** [kupriyanenko/jbone#9]
Add the ability to create custom build, like this
- `grunt build base`
- `grunt build base -attributes`
- `grunt build extend`
- `grunt build extend -manipulation,attributes`

**Comment by redaxmedia** [comment]
I can write the Grunt tasks once the extend branch was finished.

**Comment by kupriyanenko** [comment]
@redaxmedia great!

**Comment by redaxmedia** [comment]
No problem, I need that feature for my pageflip project at work :+1:

**Comment by redaxmedia** [comment]
@kupriyanenko Please provide more information, I like to resolve this issue soon.

**Comment by kupriyanenko** [comment]
Right way - split by modules, ES6 modules will not include not used code out of the box
